---
title: "Bad Vöslau"
format: html
editor: source
---



```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(scales)
  library(fs)
  library(here)
  library(sf)
  library(curl)
  library(terra)
  library(rmapshaper)
  library(tictoc)
})
```

```{r}
source(path(here(),"utils","utils.R"))
```

```{r}
load(path(here(),"vector_data", "verwaltungsgrenzen",
          "verwaltungsgrenzen_50.RData"))
```


```{r}
verwaltungsgrenzen_50 |>
get_crs()
```
```{r}
verwaltungsgrenzen_50 |>
  filter(PG=="Bad Vöslau") ->
  kat_voeslau
```

Bad Vöslau besteht aus mehreren Katastralgemeinden,
daher müssen wir zusammenfassen

```{r}
verwaltungsgrenzen_50 |>
  filter(PG=="Bad Vöslau") |>
  group_by(GKZ) |>
  summarise(geometry=st_union(geometry)) ->
  voeslau_gem
```

```{r}
get_crs(voeslau_gem)
```

```{r}
border <- vect(voeslau_gem)
```

EPSG:31256 ist an abstandsrichtiges Koordinatensystem für Österreich,
Einheit is 1m.

```{r}
border |>
  project("EPSG:31256") ->
  border_31256
ext(border_31256)
get_crs(border_31256)
```

```{r}
border |>
  project("EPSG:4326") ->
  border_4326
ext(border_4326) 
get_crs(border_4326)
```


## Gelände

```{r}
noe_raster_31256 <-
rast(path(here(),"raster_data", "gelaende",
          "niederoesterreich","noe_raster_10m_31256.tif"))  
  
```

```{r}
r_crop <- crop(noe_raster_31256,border_31256)
voeslau_raster <- mask(r_crop, border_31256)
voeslau_raster |>
  plot()
```

```{r}
voeslau_raster |>
  writeRaster(path(here(),"for_stl",
                   "voeslau_gelaende.tif"),
              overwrite=TRUE)
```

## Oberfläche

```{r}
border |>
  project("EPSG:3035") ->
  border_3035
```


```{r}
rast(path(here(), "raster_data", "oberflaeche", "oesterreich",
          "ALS_DSM_CRS3035RES50000mN2750000E4750000.tif")) ->
  noe_sw_raster_3035
  get_crs(noe_sw_raster_3035)
```

```{}
tic()
noe_ober_3035 |>
  project("EPSG:31256") ->
  noe_ober_31256
toc()
work_dir <- path(here(),"raster_data","oberflaeche","work")
dir_create(work_dir)
tic()
writeRaster(noe_ober_31256,
            path(work_dir,
                 "noe_ober_31256.tif"),
            overwrite=TRUE)
toc()
```

```{}
get_crs(noe_ober_31256)
```

```{}
border_31235
```


```{r}
work_dir <- dir_create(path(here(), "for_stl"))
tic()
r_crop <- crop(noe_sw_raster_3035,border_3035)
voeslau_ober_3035 <- mask(r_crop,border_3035)
voeslau_ober_3035 |>
  writeRaster(path(work_dir,"voeslau_ober_3035.tif"),
              overwrite=TRUE)
toc()
```

```{r}
voeslau_ober |> plot()
```

Koordinaten (lon, lat) in WGS84=EPSG:4326 in Google Maps abgelesen.
Rechteck 1x1km definieren

```{r}
c(16.207, 47.96 ) |>
  crs_transform("EPSG:4326","EPSG:3035") -> xx
xx
c(xx,xx+1000) -> xx
  ext(xx[1],xx[3],xx[2],xx[4]) ->
    kachel_3035
```
```{r}
tic()
voeslau_ober_3035 |>
   crop(kachel_3035) ->
  voes_kachel_home_3035
voes_kachel_home_3035 |>
writeRaster(path(here(),"for_stl", "voes_kachel_home_3035.tif"),
            overwrite=TRUE)
toc()
```

```{r}
voes_kachel_home_3035 |> plot()
```


```{r}
voes_kachel_home_3035 |>
writeRaster(path(work_dir, 
                 "voes_kachel_home_3035.tif"),
            overwrite=TRUE)
```

