---
title: "Kritzendorf"
format: html
editor: visual
---

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(scales)
  library(fs)
  library(here)
  library(sf)
  library(curl)
  library(tictoc)
  library(terra)
  library(rmapshaper)
  library(tidyterra)  
})
```

```{r}
source(path(here(),"utils","utils.R"))
```

```{r}
work_dir <- path(here(),"for_stl")
dir_create(work_dir)
```


## Grenzen festlegen

```{r}
load(path(here(),"vector_data", "verwaltungsgrenzen",
          "verwaltungsgrenzen_50.RData"))
```

```{r}
verwaltungsgrenzen_50 |>
get_crs()
```
Kritzendorf ist eine Katastralgemeinde der Gemeinde Klosterneuburg

```{r}
verwaltungsgrenzen_50 |>
  filter(PG=="Klosterneuburg") |>
  filter(KG=="Kritzendorf") ->
  kat_kritz
```

ogd-10m-at (Österreich Gelände)
hat EPSG:31287


```{r}
get_crs(kat_kritz)
border <- vect(kat_kritz)
project(border, "EPSG:31287") ->
  border_31287
ext(border_31287)
get_crs(border_31287)
border_31287 |>
  plot()
```

ALS_DSM (Österreich Oberfläche)
hat EPSG:3035

```{r}
get_crs(kat_kritz)
border <- vect(kat_kritz)
project(border, "EPSG:3035") ->
  border_3035
ext(border_3035)
get_crs(border_3035)
border_3035 |>
  plot()

```

## Geländemodell

```{r}
rast(
path(here(),"raster_data", "gelaende", "oesterreich", "ogd-10m-at",
     "dhm_at_lamb_10m_2018.tif")) ->
  oe_gelaende_31287
get_crs(oe_gelaende_31287)
ext(oe_gelaende_31287)
```
```{r}
oe_gelaende_31287 |> plot()
```


```{r}
r_cropped <- crop(oe_gelaende_31287,border_31287)
kritz_gelaende <- mask(r_cropped,border_31287)
kritz_gelaende |> plot()
```

```{r}
kritz_gelaende |>
writeRaster(path(work_dir,"kritz_gelaende.tif"),
            overwrite=TRUE)
```

## Oberflächenmodell




```{r}
rast(path(here(), "raster_data", "oberflaeche", "oesterreich",
          "ALS_DSM_CRS3035RES50000mN2800000E4750000.tif")) ->
  noe_sw_ober_3035
  get_crs(noe_sw_ober_3035)
```
```{r}
noe_sw_ober_3035 |>
  crop(border_3035) |>
  mask(border_3035) ->
  kritz_ober_3035
  kritz_ober_3035 |>
    plot()

```

#### Lokalisation eines Punktes

Daten eine Punktes aus Google Maps abgelesen

48.324373500741856, 16.307042687650327

```{r}
manfred_point_3035 <-
  cbind(x=16.307042687650327, y=48.324373500741856) |>
  vect(type="points", crs="EPSG:4326") |>
  project("EPSG:3035")
```

Karte mit Punkt zur Festlegung eines kleineren Aussschnitts

```{r}
plot(kritz_ober_3035) 
points(manfred_point_3035, col = "red", pch=10) 
#lines(xx |> terra::shift(0,1000),
#      col="red")
```





```{r}
point_to_rect(manfred_point_3035) |> str()
  plot()
```


```{r}
plot(kritz_ober_3035) 
points(manfred_point_3035, col = "red", pch=10) 
lines(
point_to_rect(manfred_point_3035) |>
  shift(0,110),
col="red"
) 
```

```{r}
point_to_rect(manfred_point_3035) |>
  shift(0,110) |>
  ext() ->
  manfred_kachel_3035
```

```{r}
kritz_ober_3035 |>
  crop(manfred_kachel_3035) |>
  mask(manfred_kachel_3035) ->
  kritz_manfred_3035
```



```{r}
kritz_manfred_3035 |> plot()

writeRaster(kritz_manfred_3035,
            path(here(),"for_stl",
                 "kritz_manfred_3035.tif"),
            overwrite=TRUE)
```
